package Calculator;


/**
* Calculator/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Saturday, 20 May, 2023 12:43:51 PM IST
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
